# -*- coding: utf-8 -*-
"""python using ai project 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckoXrZt8uTGyG411xvTc64FrPkB3Azut
"""

# Calculator

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Cannot divide by zero!"
    return a / b

print(" Welcome to Python Calculator!")
print("Choose an operation:")
print("1. Add")
print("2. Subtract")
print("3. Multiply")
print("4. Divide")

choice = input("Enter choice (1/2/3/4): ")

# to get user inputs
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))

# excecuting the operation
if choice == '1':
    result = add(a, b)
    print(f"Result: {a} + {b} = {result}")

elif choice == '2':
    result = subtract(a, b)
    print(f"Result: {a} - {b} = {result}")

elif choice == '3':
    result = multiply(a, b)
    print(f"Result: {a} * {b} = {result}")

elif choice == '4':
    result = divide(a, b)
    print(f"Result: {a} / {b} = {result}")

else:
    print(" Invalid input. Please choose 1, 2, 3, or 4.")

